# Generated by Django 3.1 on 2021-01-21 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_user_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gestion.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='profil_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
