# Generated by Django 3.1 on 2021-01-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupeCompetences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Competences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250)),
                ('groupeCompetences', models.ManyToManyField(to='gestion.GroupeCompetences')),
            ],
            options={
                'ordering': ['libelle'],
            },
        ),
    ]
