# Generated by Django 3.1 on 2021-01-25 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_auto_20210125_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupecompetences',
            name='competences',
        ),
        migrations.AlterField(
            model_name='competences',
            name='groupeCompetences',
            field=models.ManyToManyField(blank=True, related_name='competences', to='gestion.GroupeCompetences'),
        ),
    ]
