# Generated by Django 3.1 on 2021-01-25 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_auto_20210125_0031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competences',
            old_name='groupeCompetences',
            new_name='GroupeCompetences',
        ),
    ]
