# Generated by Django 3.1 on 2021-01-25 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_auto_20210125_0114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competences',
            old_name='GroupeCompetences',
            new_name='groupeCompetences',
        ),
    ]
