# Generated by Django 3.1 on 2021-01-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_auto_20210125_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Niveaux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupeAction', models.CharField(max_length=200)),
                ('critereEvaluation', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='competences',
            name='niveaux',
            field=models.ManyToManyField(blank=True, related_name='competences', to='gestion.Niveaux'),
        ),
    ]
