# Generated by Django 3.1 on 2021-01-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_auto_20210125_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referentiel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250)),
                ('presentation', models.TextField(max_length=1000)),
                ('programme', models.FileField(upload_to='')),
                ('critereAction', models.TextField(max_length=1000)),
                ('critereAdmission', models.TextField(max_length=1000)),
                ('competences', models.ManyToManyField(blank=True, to='gestion.Competences')),
            ],
        ),
    ]
