# Generated by Django 3.1 on 2021-01-26 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_auto_20210126_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referentiel',
            old_name='critereAction',
            new_name='critereEvaluation',
        ),
    ]
